=== SolarHauks/Game-XML/Content/Data/Highscore/highscore.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="scores" type="Score"/>

    <xs:complexType name="Score">
        <xs:sequence>
            <xs:element name="temps" type="xs:float" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== SolarHauks/Game-XML/Content/Data/Highscore/score.xml
<?xml version="1.0" encoding="utf-8"?>
<scores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="highscore.xsd">
  <temps>7.07</temps>
  <temps>13.68</temps>
  <temps>15.08</temps>
  <temps>5.35</temps>
  <temps>0.1</temps>
  <temps>11.57</temps>
  <temps>5.20</temps>
  <temps>5.85</temps>
  <temps>5.78</temps>
  <temps>6.20</temps>
  <temps>7.13</temps>
  <temps>9.32</temps>
  <temps>9.17</temps>
  <temps>8.97</temps>
  <temps>8.90</temps>
  <temps>9.17</temps>
  <temps>22.80</temps>
</scores>
